kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "pxc-operator.fullname" . }}
  {{- if .Values.watchNamespace }}
  namespace: {{ .Values.watchNamespace }}
  {{- end }}
  labels:
{{ include "pxc-operator.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: default
  {{- if .Values.watchNamespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
roleRef:
  {{- if .Values.watchNamespace }}
  kind: ClusterRole
  {{- else }}
  kind: Role
  {{- end }}
  name: {{ include "pxc-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
